// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "swapi-indra",
    "version": "1"
  },
  "paths": {
    "/starships/get-from-swapi": {
      "get": {
        "summary": "swapiStarshipsRoutes",
        "description": "",
        "operationId": "swapiStarshipsRoutes.get.starships/get-from-swapi",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/starships/get": {
      "get": {
        "summary": "localStarshipsRoutes",
        "description": "",
        "operationId": "localStarshipsRoutes.get.starships/get",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/starship": {
      "post": {
        "summary": "starshipRoutes",
        "description": "",
        "operationId": "starshipRoutes.post.starship",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};